name: DORA - Trigger Deployments from Labels

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  actions: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.get-labels.outputs.labels }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR labels for this commit
        id: get-labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitSha = '${{ github.sha }}';
            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha,
            });

            if (prs.data.length === 0) {
              console.log('❌ Nenhum PR encontrado para o commit.');
              core.setOutput('labels', '[]');
              return;
            }

            const prNumber = prs.data[0].number;
            console.log(`✅ PR encontrado: #${prNumber}`);

            const labelsResponse = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });

            const labels = labelsResponse.data.map(label => label.name);
            console.log('✅ Labels encontradas:', labels);
            core.setOutput('labels', JSON.stringify(labels));

  deploy:
    needs: prepare
    if: ${{ needs.prepare.outputs.labels != '[]' && needs.prepare.outputs.labels != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{ fromJson(needs.prepare.outputs.labels) }}
    name: Deploy ${{ matrix.label }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy for ${{ matrix.label }}
        run: |
          echo "🚀 Executando deploy para serviço: ${{ matrix.label }}"