name: Trigger Deployments from Labels

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read
  pull-requests: read
  actions: write

jobs:
  prepare:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.get-labels.outputs.labels }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR labels from event
        id: get-labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);
            console.log('✅ Labels encontradas no PR:', labels);
            core.setOutput('labels', JSON.stringify(labels));

  deploy:
    needs: prepare
    if: ${{ needs.prepare.outputs.labels != '[]' && needs.prepare.outputs.labels != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ${{ fromJson(needs.prepare.outputs.labels) }}
    name: Deploy ${{ matrix.label }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy for ${{ matrix.label }}
        run: |
          echo "🚀 Executando deploy para serviço: ${{ matrix.label }}"
